spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springdb?createDatabaseIfNotExists=true
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver  
  
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9292/oauth/check_token
    client:
      client-id: mhh
      client-secret: 1234
    